server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
          server-addr: localhost:8848
        # 换成nginx的1111端口
       # server-addr: 192.68.111.144:1111

management:
  endpoints:
    web:
      exposure:
        include: "*"