server:
  port: 7001


eureka:
  instance:
    hostname: eureka7001.com
  client:
    #false表示不像注册中心注册自己
    register-with-eureka: false
    #false表示自己端就是注册中心,我的职责就是维护服务实例,并不需要检索服务
    fetch-registry: false
    service-url:
      #集群模式
        # defaultZone: http://eureka7002.com:7002/eureka/
      #单机就是自己
      defalutZone: http://eureka7001.com:7001/eureka/
#  server:
#    enable-self-preservation: false
#    eviction-interval-timer-in-ms: 2000
